name: JeremyStuart
favicon: null
layout_spectrum: 1
typography_spectrum: 0.51672
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0dfdd'
    - '#000000'
    - '#7dd29f'
    - '#303030'
    - '#838383'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
